name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:  # To allow manual runs.
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages  # Only allow one deployment at a time.
  cancel-in-progress: false  # Don't cancel in-progress ones in case later ones fail.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    - name: Copy the PDF to _site/
      run: mkdir -p _site && cp output/main.pdf _site/
    - name: Prepare the GH Pages content
      uses: actions/upload-pages-artifact@v2
    - name: Deploy to GH Pages
      uses: actions/deploy-pages@v2
