name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    - name: Copy the PDF to dist/
      run: mkdir -p dist && cp output/main.pdf dist/
    - name: Commit dist/ to gh-pages branch
      uses: bryant1410/ghpages@patch-1
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
